feat: add GenDigital implementation
w3c-ccg/vc-test-suite-implementations pull request #116
Opened 2024-12-02 22:39 UTC by skynet2

2024-12-03 14:17 UTC, sudeshrshetty commented
@BigBlueHat please review and merge

2024-12-03 22:28 UTC, BigBlueHat commented
@skynet2 @sudeshrshetty same thing needed as on https://github.com/w3c/vc-test-suite-implementations/pull/84#issuecomment-2515626476

The `id` needs to be a URI--ideally a `did:key`.

2024-12-04 10:58 UTC, skynet2 commented
hi @BigBlueHat ,
Updated, please review.

Thanks,
Stas

2024-12-04 16:22 UTC, PatStLouis approved these changes
@skynet2 fyi the BitstringStatusList test suites have migrated to the w3c and don't need to be duplicated here as you have included them in the w3c implementations.

2024-12-04 20:31 UTC, BigBlueHat commented
> @skynet2 fyi the BitstringStatusList test suites have migrated to the w3c and don't need to be duplicated here as you have included them in the w3c implementations. Otherwise this looks good!

Can you remove the `BitstringStatusList` entries? Those are covered by your other PR: https://github.com/w3c/vc-test-suite-implementations/pull/84

Otherwise, this looks good!

2024-12-04 20:32 UTC, BigBlueHat requested changes

2024-12-04 20:32 UTC, BigBlueHat commented on implementations/GenDigital.json
> +    }
```suggestion
    }
```

2024-12-04 20:32 UTC, BigBlueHat commented on implementations/GenDigital.json
> +    }
```suggestion
    }
```

2024-12-05 13:57 UTC, skynet2 commented
hi @BigBlueHat ,
Thanks for the patch. I applied it.

Thanks,
Stas

2024-12-05 14:04 UTC, fqutishat commented
Hi @BigBlueHat  can you please review the PR we made the change that requested

2024-12-05 16:28 UTC, PatStLouis approved these changes

2024-12-05 16:29 UTC, merged

2024-12-06 02:19 UTC, sudeshrshetty commented
@PatStLouis Can you please generate latest interop report for vc-api issuer & verifier test suites.